// Centralized Korean UI strings. Keep all user-facing copy here for easy review.

export const copy = {
  appName: "30분 화성 AI 맵",
  landing: {
    tagline: "시민이 말하면, AI가 정리하고 지도로 보여줍니다.",
    description:
      "교통불편을 글로 남겨주시면 AI가 자동으로 분류하고 지도에 표시해 화성시 교통 정책에 반영합니다.",
    reportCta: "교통불편 제보하기",
    mapCta: "교통불편 지도 보기",
  },
  report: {
    title: "교통불편 제보하기",
    subtitle: "겪으신 교통 불편을 자유롭게 적어주시면 AI가 정리해드립니다.",
    descriptionLabel: "어떤 교통 불편을 겪으셨나요?",
    descriptionPlaceholder:
      "예) 매일 아침 8시쯤 이 정류장에서 버스를 15분 넘게 기다려요. 배차 간격이 너무 길어요.",
    locationLabel: "위치/장소명",
    locationPlaceholder: "예) 동탄역 2번 출구 버스정류장",
    timePatternLabel: "자주 발생하는 시간대",
    timePatternPlaceholder: "선택해주세요",
    transportModeLabel: "교통수단",
    transportModePlaceholder: "선택해주세요",
    targetGroupsLabel: "이용자 유형 (해당되는 항목 모두 선택, 선택사항)",
    severityLabel: "체감 불편도",
    severityHint: "1 (약함) ~ 5 (심각)",
    photoLabel: "사진 첨부 (선택사항)",
    photoHint: "현재는 미리보기만 지원되며, 실제 업로드는 추후 지원됩니다.",
    submit: "제보 내용 확인하기",
    errors: {
      description: {
        required: "어떤 교통 불편을 겪으셨는지 입력해주세요.",
        min: "10자 이상 입력해주세요.",
        max: "2000자 이하로 입력해주세요.",
      },
      locationName: "위치/장소명을 입력해주세요.",
      timePattern: "자주 발생하는 시간대를 선택해주세요.",
      transportMode: "교통수단을 선택해주세요.",
    },
    analyzing: "AI가 제보 내용을 분석하고 있어요...",
    analyzeError:
      "AI 분석에 실패했습니다. 잠시 후 다시 시도해주세요. 문제가 계속되면 관리자에게 문의해주세요.",
    retry: "다시 시도",
  },
  review: {
    title: "제보 내용 확인",
    subtitle:
      "AI가 정리한 내용이에요. 개인정보는 자동으로 가려졌습니다. 이대로 등록하거나 다시 작성해주세요.",
    maskedTextLabel: "정리된 제보 내용 (개인정보 마스킹 완료)",
    summaryLabel: "AI 한줄 요약",
    subCategoryLabel: "세부 유형",
    problemTypesLabel: "문제 유형",
    locationLabel: "위치/장소명",
    timePatternLabel: "시간대",
    transportModeLabel: "교통수단",
    severityLabel: "체감 불편도",
    targetGroupsLabel: "이용자 유형",
    suggestedPoliciesLabel: "AI 정책 제안 (참고용)",
    confirm: "이대로 등록",
    edit: "수정하기",
    saving: "저장 중...",
    saveSuccess: "제보가 등록되었습니다. 소중한 의견 감사합니다!",
    saveError: "제보 저장에 실패했습니다. 잠시 후 다시 시도해주세요.",
  },
  reportsList: {
    title: "등록된 제보 목록 (임시 확인용)",
    empty: "아직 등록된 제보가 없습니다.",
  },
  clustersDebug: {
    title: "클러스터 및 우선순위 점수 (임시 확인용)",
    empty: "아직 생성된 클러스터가 없습니다.",
    scoreLabel: "우선순위 점수",
    reportCountLabel: "제보 건수",
    breakdownTitle: "점수 세부 내역 (가중치)",
  },
  map: {
    title: "교통불편 지도",
    subtitle: "화성시 시민들이 제보한 교통 불편을 지도에서 확인하세요.",
    filters: {
      district: "지역",
      transportMode: "교통수단",
      timePattern: "시간대",
      subCategory: "불편 유형",
      all: "전체",
      reset: "필터 초기화",
    },
    popup: {
      severity: "체감 불편도",
    },
    topIssues: {
      title: "현재 가장 많이 제보된 이슈 TOP 5",
      countSuffix: "건",
      empty: "아직 집계할 이슈가 없습니다.",
    },
    empty: "아직 제보가 없습니다.",
    loading: "지도를 불러오는 중...",
    loadError: "제보 목록을 불러오지 못했습니다. 잠시 후 다시 시도해주세요.",
    resultCount: "건의 제보가 지도에 표시되고 있습니다.",
  },
  admin: {
    loginTitle: "관리자 로그인",
    loginSubtitle: "화성시 교통불편 관리자 대시보드입니다.",
    passphraseLabel: "비밀번호",
    loginSubmit: "로그인",
    loginError: "비밀번호가 올바르지 않습니다.",
    logout: "로그아웃",
    dashboardTitle: "관리자 대시보드",
    kpis: {
      totalReports: "총 제보 수",
      newThisWeek: "이번 주 신규 제보 수",
      topSubCategory: "가장 많은 불편 유형",
      topDistrict: "가장 많이 언급된 지역",
      nightGapReports: "심야 교통 공백 제보 수",
      vulnerableReports: "교통약자 관련 제보 수",
      none: "-",
    },
    charts: {
      bySubCategory: "불편 유형별 제보 수",
      byDistrict: "지역별 제보 수",
      countSuffix: "건",
    },
    clusterList: {
      title: "우선순위 클러스터 목록",
      empty: "아직 생성된 클러스터가 없습니다.",
      priority: "우선순위",
      reportCount: "제보",
    },
    clusterDetail: {
      back: "← 목록으로",
      representativeTitle: "대표 제보",
      memberReportsTitle: "포함된 제보",
      breakdownTitle: "점수 세부 내역",
    },
    policyReport: {
      generate: "정책 검토 보고서 생성",
      regenerate: "다시 생성",
      generating: "보고서를 생성하는 중...",
      generateError: "정책 보고서 생성에 실패했습니다. 잠시 후 다시 시도해주세요.",
      retry: "다시 시도",
      copy: "복사",
      copied: "복사됨",
      download: "다운로드(.md)",
      title: "정책 검토 보고서",
      generatedAt: "생성 시각",
    },
    transitEvidence: {
      title: "실측 데이터 근거 (경기버스정보)",
      stationLabel: "정류소",
      routeLabel: "노선",
      arrival1: "다음 도착",
      arrival2: "그 다음 도착",
      minutesSuffix: "분 후",
      crowdedLabel: "혼잡도",
      currentLocationLabel: "현재 위치",
      liveLabel: "실시간 데이터",
      cachedLabel: "캐시된 데이터 (실시간 조회 실패 시 대체 표시)",
      loading: "실시간 버스 정보를 불러오는 중...",
      error: "실측 데이터를 불러오지 못했습니다.",
      crowdedLevels: ["여유", "보통", "혼잡", "매우 혼잡"],
    },
  },
} as const;
