import type { GbisArrivalItem } from "@/lib/gbis";

// Demo safety net (see docs/phases/phase-08-public-data-integration.md): if the
// live GBIS API is down or rate-limited, /api/transit serves this cached
// snapshot instead of failing outright. The UI must always label this
// clearly as cached, never pass it off as live.
//
// Captured live from every route serving 수영오거리.방송통신대입구
// (화성시 봉담읍) that had a bus actively tracked at capture time. Routes
// with no bus currently running (GBIS returns "" for every field) are
// omitted here, same as fetchAllArrivalsForStation does for live calls.
export const TRANSIT_FALLBACK_SNAPSHOT: {
  capturedAt: string;
  items: GbisArrivalItem[];
} = {
  capturedAt: "2026-07-06T21:13:50+09:00",
  items: [
    {
      stationId: 233000839,
      routeId: 200000265,
      routeName: "30-1",
      staOrder: 35,
      flag: "PASS",
      predictTime1: 1,
      predictTimeSec1: 80,
      predictTime2: 12,
      predictTimeSec2: 758,
      remainSeatCnt1: 0,
      remainSeatCnt2: 0,
      crowded1: 1,
      crowded2: 1,
      stationNm1: "오목천역.영신여자고교.청구아",
      stationNm2: "중보교.수원역자동차운전전문학",
    },
    {
      stationId: 233000839,
      routeId: 200000148,
      routeName: "35",
      staOrder: 32,
      flag: "PASS",
      predictTime1: 3,
      predictTimeSec1: 214,
      predictTime2: 13,
      predictTimeSec2: 814,
      remainSeatCnt1: 0,
      remainSeatCnt2: 0,
      crowded1: 1,
      crowded2: 1,
      stationNm1: "오목천동사거리",
      stationNm2: "중보교.수원역자동차운전전문학",
    },
    {
      stationId: 233000839,
      routeId: 233000271,
      routeName: "9802",
      staOrder: 11,
      flag: "PASS",
      predictTime1: 6,
      predictTimeSec1: 421,
      predictTime2: null,
      predictTimeSec2: null,
      remainSeatCnt1: 28,
      remainSeatCnt2: 0,
      crowded1: 1,
      crowded2: 0,
      stationNm1: "고색역.고색초교.태산아파트",
      stationNm2: null,
    },
    {
      stationId: 233000839,
      routeId: 233000272,
      routeName: "8472",
      staOrder: 12,
      flag: "PASS",
      predictTime1: 11,
      predictTimeSec1: 692,
      predictTime2: null,
      predictTimeSec2: null,
      remainSeatCnt1: 35,
      remainSeatCnt2: 0,
      crowded1: 1,
      crowded2: 0,
      stationNm1: "벌말교차로(미정차)",
      stationNm2: null,
    },
    {
      stationId: 233000839,
      routeId: 233000083,
      routeName: "30",
      staOrder: 36,
      flag: "PASS",
      predictTime1: 31,
      predictTimeSec1: 1909,
      predictTime2: null,
      predictTimeSec2: null,
      remainSeatCnt1: 0,
      remainSeatCnt2: 0,
      crowded1: 1,
      crowded2: 0,
      stationNm1: "정자3동행정복지센터.정자동중",
      stationNm2: null,
    },
    {
      stationId: 233000839,
      routeId: 233000011,
      routeName: "34",
      staOrder: 69,
      flag: "PASS",
      predictTime1: 46,
      predictTimeSec1: 2778,
      predictTime2: 80,
      predictTimeSec2: 4816,
      remainSeatCnt1: 0,
      remainSeatCnt2: 0,
      crowded1: 1,
      crowded2: 1,
      stationNm1: "안화초교.주공8.9단지",
      stationNm2: "황골마을",
    },
    {
      stationId: 233000839,
      routeId: 241488006,
      routeName: "31-2",
      staOrder: 42,
      flag: "PASS",
      predictTime1: 61,
      predictTimeSec1: 3652,
      predictTime2: null,
      predictTimeSec2: null,
      remainSeatCnt1: -1,
      remainSeatCnt2: 0,
      crowded1: 0,
      crowded2: 0,
      stationNm1: "수원과학대학",
      stationNm2: null,
    },
  ],
};
